[phases.setup]
nixPkgs = ["python311", "nodejs_20"]

[phases.install]
cmds = [
    "python -m venv /app/.venv",
    "pip install -r requirements.txt",
    "cd webapp && npm install"
]

[phases.build]
cmds = ["cd webapp && npm run build"]

[start]
cmd = "python -m src.main"
